test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4da53256350d7e4d63812ed3244e945346a5d9b7.name = "Upgrade from 2.3.8~ynh4"
