test_format = 1.0

[default]


    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.language = "fr"
    args.name = "wallabag"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e9459b2bc46728427bda81e2043f3b4116771e2d.name = "Upgrade from 2.5.4~ynh2"
