test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.bac6d108163e7ef7f4d36296aeb4f299258ced29.name = "Upgrade from 2.5.4~ynh2"
