parameters:
    database_driver: ${DATABASE_DRIVER:-pdo_mysql}
    database_host: ${DATABASE_HOST:-127.0.0.1}
    database_port: ${DATABASE_PORT:-~}
    database_name: ${DATABASE_NAME:- _DB_NAME__}
    database_user: ${DATABASE_USER:-__DB_USER__}
    database_password: ${DATABASE_PASSWORD:-__DB_PWD__}
    database_path: ${DATABASE_PATH:-"%kernel.project_dir%/data/db/wallabag.sqlite"}
    database_table_prefix: ${DATABASE_TABLE_PREFIX:-__APP___}
    database_socket: ${DATABASE_SOCKET:-~}
    database_charset: ${DATABASE_CHARSET:-utf8mb4}

    domain_name: ${DOMAIN_NAME:-https://www.example.com}
    server_name: ${SERVER_NAME:-"Your wallabag instance"}

    mailer_dsn: ${MAILER_DSN:-"smtp://127.0.0.1"}

    locale: ${LOCALE:-en}

    # A secret key that's used to generate certain security-related tokens
    secret: __DESKEY__

    # two factor stuff
    twofactor_sender: ${TWOFACTOR_SENDER:-__APP__@__DOMAIN__}

    # fosuser stuff
    fosuser_registration: ${FOSUSER_REGISTRATION:-false}
    fosuser_confirmation: ${FOSUSER_CONFIRMATION:-true}

    fos_oauth_server_access_token_lifetime: ${FOS_OAUTH_SERVER_ACCESS_TOKEN_LIFETIME:-3600}
    fos_oauth_server_refresh_token_lifetime: ${FOS_OAUTH_SERVER_REFRESH_TOKEN_LIFETIME:-1209600}

    from_email: ${FROM_EMAIL:-__APP__@__DOMAIN__}

    # RabbitMQ processing
    rabbitmq_host: ${RABBITMQ_HOST:-localhost}
    rabbitmq_port: ${RABBITMQ_PORT:-5672}
    rabbitmq_user: ${RABBITMQ_USER:-guest}
    rabbitmq_password: ${RABBITMQ_PASSWORD:-guest}
    rabbitmq_prefetch_count: ${RABBITMQ_PREFETCH_COUNT:-10}

    # Redis processing
    redis_scheme: ${REDIS_SCHEME:-tcp}
    redis_host: ${REDIS_HOST:-localhost}
    redis_port: ${REDIS_PORT:-6379}
    redis_path: ${REDIS_PATH:-~}
    redis_password: ${REDIS_PASSWORD:-~}

    # Sentry
    sentry_dsn: ${SENTRY_DSN:-~}