parameters:
    database_driver: pdo_mysql
    database_driver_class: ~
    database_host: 127.0.0.1
    database_port: ~
    database_name: __DB_NAME__
    database_user: __DB_USER__
    database_password: __DB_PWD__
    database_path: ~
    database_table_prefix: wallabag_
    database_socket: ~
    database_charset: utf8mb4
    domain_name: https://__DOMAIN____PATH__
    mailer_dsn: smtp://__APP__:__MAIL_PWD__@__DOMAIN__:25
    locale: __LANGUAGE__
    secret: __DESKEY__
    twofactor_auth: true
    twofactor_sender: no-reply@__DOMAIN__
    fosuser_registration: true
    fosuser_confirmation: true
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: no-reply@__DOMAIN__
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: ~
    redis_password: ~
    sentry_dsn: ~
    server_name: "__NAME__"
