# This file is a "template" of what your parameters.yml file should look like
parameters:
    
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: __DB_NAME__
    database_user: __DB_USER__
    database_password: __DB_PWD__
    # For SQLite, database_path should be "%kernel.project_dir%/data/db/wallabag.sqlite"
    database_path: null
    database_table_prefix: null
    database_socket: null
    # with PostgreSQL and SQLite, you must set "utf8"
    database_charset: utf8mb4

    domain_name: 'https://__DOMAIN____PATH__'
    server_name: 'Your wallabag instance'

    mailer_dsn: 'smtp://__APP__:__MAIL_PWD__@127.0.0.1:587'

    wallabag_user_agent: "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.2 (KHTML, like Gecko) Chrome/15.0.874.92 Safari/535.2"

    locale: en

    # A secret key that's used to generate certain security-related tokens
    secret: '__DESKEY__'

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: __APP__@__DOMAIN__

    # fosuser stuff
    fosuser_registration: false
    fosuser_confirmation: true

    # how long the access token should live in seconds for the API
    fos_oauth_server_access_token_lifetime: 3600
    # how long the refresh token should life in seconds for the API
    fos_oauth_server_refresh_token_lifetime: 1209600

    from_email: __APP__@__DOMAIN__

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null

    # sentry logging
    sentry_dsn: null
