parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: {DBNAME}
    database_user: {DBUSER}
    database_password: {DBPASS}
    database_path: null
    database_table_prefix: null
    database_socket: null
    database_charset: utf8mb4

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       null
    mailer_password:   null

    locale:            en

    # A secret key that's used to generate certain security-related tokens
    secret:            {DESKEY}

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_registration: false
    fosuser_confirmation: true

    from_email: no-reply@wallabag.org

    rss_limit: 50

    # RabbitMQ processing
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10

    # Redis processing
    redis_scheme: tcp
    redis_host: localhost
    redis_port: 6379
    redis_path: null
    redis_password: null
 
    # sites credentials
    sites_credentials: {}
