#!/bin/bash

app="__APP__"
user="__APP__"
install_dir=$(ynh_app_setting_get --app="$app" --key=install_dir)
phpversion=$(ynh_app_setting_get --app="$app" --key=phpversion)

# Retrieve arguments
username=$1
user_email=$2

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Generate a random password
user_pass=$(ynh_string_random)

# Create the new user in Wallabag
pushd "$install_dir" || ynh_die
    sudo -u "$user" "php$phpversion" "bin/console" --no-interaction --env=prod \
        fos:user:create "$username" "$user_email" "$user_pass"
popd || ynh_die
