#!/bin/bash

app="__APP__"
user="__APP__"

# Retrieve arguments
username=$1
purge=$2

# Deactivate the user from Wallabg
(cd "/var/www/$app" && \
 sudo -u "$user" php${phpversion} "bin/console" --no-interaction --env=prod \
    fos:user:deactivate "$username")
