#!/bin/bash

app="wallabag2"
user="wallabag2"

# Retrieve arguments
username=$1
purge=$2

# Deactivate the user from Wallabg
(cd "/var/www/$app" && \
 sudo -u "$user" php "bin/console" --no-interaction --env=prod \
    fos:user:deactivate "$username")
